export enum EnvironmentVariable {
    TARGET_ENV = "REACT_APP_TARGET_ENV",
    APP_URL = "REACT_APP_URL",
    WEBAPP_URL = "REACT_APP_WEBAPP_URL",
    APP_VERSION = "REACT_APP_VERSION",
    APP_VERSION_FULL = "REACT_APP_VERSION_FULL",
    API_ENDPOINT = "REACT_APP_API_ENDPOINT",
    DEPLOY_PATH = "REACT_APP_DEPLOY_PATH",
    DEPLOY_TIME = "REACT_APP_DEPLOY_TIME",
    INTERCOM_APPID = "REACT_APP_INTERCOM_APPID",
    DATADOG_KEY = "REACT_APP_DATADOG_KEY",
    APPLE_ID_CLIENT_ID = "REACT_APP_APPLE_ID_CLIENT_ID",
    GOOGLE_IDENTITY_CLIENT_ID = "REACT_APP_GOOGLE_IDENTITY_CLIENT_ID",
}

